// Sonda del taller: con dinero, abre el garaje, compra el tubarro y comprueba que la moto cambia.
import { chromium } from 'playwright-core';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { join, extname } from 'node:path';
const DIST = new URL('../dist/', import.meta.url).pathname;
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.png': 'image/png' };
const srv = createServer(async (req, res) => { let r = new URL(req.url, 'http://x').pathname; if (r.endsWith('/')) r += 'index.html'; try { res.writeHead(200, { 'content-type': MIME[extname(r)] ?? 'application/octet-stream' }); res.end(await readFile(join(DIST, r))); } catch { res.writeHead(404); res.end(); } });
await new Promise((r) => srv.listen(0, '127.0.0.1', r));
const url = `http://127.0.0.1:${srv.address().port}/?barrio=pino-montano`;
const b = await chromium.launch({ executablePath: '/usr/bin/chromium', args: ['--no-sandbox', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 390, height: 844 } });
p.on('console', (m) => { if (m.type() === 'error') console.log('ERR', m.text()); });
p.on('pageerror', (e) => console.log('PAGEERR', String(e)));
await p.goto(url, { waitUntil: 'load' });
await p.waitForFunction(() => window.__pv_listo === true, null, { timeout: 120000 });
await p.click('#boton-jugar');
await p.evaluate(() => window.__pv_prueba.dinero(500));
const antes = await p.evaluate(() => window.__pv_prueba.ajustes());
await p.keyboard.press('Escape');
await new Promise((r) => setTimeout(r, 400));
await p.click('#menu [data-pestana="garaje"]');
await new Promise((r) => setTimeout(r, 300));
await p.screenshot({ path: 'logs/captura-taller.png' });
console.log('botones', await p.evaluate(() => [...document.querySelectorAll('#menu [data-mejora]')].map((b) => `${b.dataset.mejora}:${b.textContent}:${b.disabled}`)));
await p.click('#menu [data-mejora="escape"]');
await new Promise((r) => setTimeout(r, 400));
const despues = await p.evaluate(() => window.__pv_prueba.ajustes());
console.log('punta', antes.velocidadMaxima, '→', despues.velocidadMaxima, 'dinero', await p.evaluate(() => document.getElementById('hud-dinero').textContent));
console.log('niveles', await p.evaluate(() => [...document.querySelectorAll('#menu .mejora .niveles')].map((n) => n.querySelectorAll('.lleno').length)));
await p.screenshot({ path: 'logs/captura-taller-2.png' });
await b.close(); srv.close();
