// Sonda: carga un barrio (?barrio=id), mide render y update, y hace una captura.
import { chromium } from 'playwright-core';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { join, extname } from 'node:path';
const DIST = '/home/idarroniz/pinoloko/dist';
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.png': 'image/png' };
const srv = createServer(async (req, res) => { let r = new URL(req.url, 'http://x').pathname; if (r.endsWith('/')) r += 'index.html'; try { res.writeHead(200, { 'content-type': MIME[extname(r)] ?? 'application/octet-stream' }); res.end(await readFile(join(DIST, r))); } catch { res.writeHead(404); res.end(); } });
await new Promise((r) => srv.listen(0, '127.0.0.1', r));
const barrio = process.argv[2] ?? 'alameda';
const url = `http://127.0.0.1:${srv.address().port}/?barrio=${barrio}`;
const b = await chromium.launch({ executablePath: '/usr/bin/chromium', args: ['--no-sandbox', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 390, height: 844 } });
p.on('console', (m) => { if (m.type() === 'error') console.log('ERR', m.text()); });
p.on('pageerror', (e) => console.log('PAGEERR', String(e)));
await p.goto(url, { waitUntil: 'load' });
const t0 = Date.now();
await p.waitForFunction(() => window.__pv_listo === true, null, { timeout: 120000 });
console.log('carga ms', Date.now() - t0);
await p.click('#boton-jugar');
await new Promise((r) => setTimeout(r, 3000));
await p.evaluate(() => { performance.clearMeasures('update'); performance.clearMeasures('render'); });
const f0 = await p.evaluate(() => window.__pv_frames);
await p.keyboard.down('w');
await new Promise((r) => setTimeout(r, 8000));
await p.keyboard.up('w');
const f1 = await p.evaluate(() => window.__pv_frames);
const med = (n) => `const m = performance.getEntriesByName('${n}').map((e) => e.duration).sort((a, b) => a - b); return m.length ? m[Math.floor(m.length / 2)] : -1;`;
console.log('frames en 8 s', f1 - f0);
console.log('mediana update', await p.evaluate(new Function(med('update'))));
console.log('mediana render', await p.evaluate(new Function(med('render'))));
const i = await p.evaluate(() => window.__pv_info());
console.log(JSON.stringify({ barrio: i.barrio, render: i.render, memoria: i.memoria, trastos: i.trastos, cuerpos: i.cuerpos, trafico: i.trafico, paradas: i.paradas, vehiculo: i.vehiculo }));
await p.screenshot({ path: `logs/captura-${barrio}.png` });
await b.close(); srv.close();
