// Sonda: con el camión de Lipasam robado, parar junto a un contenedor lo recoge y paga 5 €.
import { chromium } from 'playwright-core';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { join, extname } from 'node:path';
const DIST = '/home/idarroniz/pinoloko/dist';
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.png': 'image/png' };
const srv = createServer(async (req, res) => { let r = new URL(req.url, 'http://x').pathname; if (r.endsWith('/')) r += 'index.html'; try { res.writeHead(200, { 'content-type': MIME[extname(r)] ?? 'application/octet-stream' }); res.end(await readFile(join(DIST, r))); } catch { res.writeHead(404); res.end(); } });
await new Promise((r) => srv.listen(0, '127.0.0.1', r));
const b = await chromium.launch({ executablePath: '/usr/bin/chromium', args: ['--no-sandbox', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 390, height: 844 } });
const errores = [];
p.on('console', (m) => { if (m.type() === 'error') errores.push(m.text()); });
p.on('pageerror', (e) => errores.push(String(e)));
const dormir = (ms) => new Promise((r) => setTimeout(r, ms));
await p.goto(`http://127.0.0.1:${srv.address().port}/?barrio=${process.argv[2] ?? 'pino-montano'}`, { waitUntil: 'load' });
await p.waitForFunction(() => window.__pv_listo === true, null, { timeout: 120000 });
await p.click('#boton-jugar');
await dormir(1500);
console.log('robar camión:', await p.evaluate(() => window.__pv_prueba.robarCamion()));
const contenedores = await p.evaluate(() => window.__pv_prueba.trastos('contenedor'));
console.log('contenedores:', contenedores.length);
const [cx, cz] = contenedores[0];
await p.evaluate(([x, z]) => window.__pv_prueba.irCoche(x + 3, z), [cx, cz]);
await dormir(5000);
console.log('dinero:', await p.evaluate(() => document.querySelector('#hud-dinero').textContent), 'contenedores ahora:', (await p.evaluate(() => window.__pv_prueba.trastos('contenedor'))).length, 'aviso:', await p.evaluate(() => document.querySelector('#aviso').textContent));
const esperando0 = await p.evaluate(() => window.__pv_info().esperando);
await dormir(20000);
console.log('esperando en marquesinas antes/después (el 13 del tráfico va y viene):', esperando0, '→', await p.evaluate(() => window.__pv_info().esperando));
console.log(errores.length ? `ERRORES: ${errores.slice(0, 3).join('\n')}` : 'sin errores');
await b.close(); srv.close();
process.exit(errores.length ? 1 : 0);
