// Sonda: el 13 circula, se le roba y se conduce; hay vecinos sentados en las terrazas.
import { chromium } from 'playwright-core';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { join, extname } from 'node:path';
const DIST = '/home/idarroniz/pinoloko/dist';
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.png': 'image/png' };
const srv = createServer(async (req, res) => { let r = new URL(req.url, 'http://x').pathname; if (r.endsWith('/')) r += 'index.html'; try { res.writeHead(200, { 'content-type': MIME[extname(r)] ?? 'application/octet-stream' }); res.end(await readFile(join(DIST, r))); } catch { res.writeHead(404); res.end(); } });
await new Promise((r) => srv.listen(0, '127.0.0.1', r));
const barrio = process.argv[2] ?? 'pino-montano';
const b = await chromium.launch({ executablePath: '/usr/bin/chromium', args: ['--no-sandbox', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 390, height: 844 } });
p.on('console', (m) => { if (m.type() === 'error') console.log('ERR', m.text()); });
p.on('pageerror', (e) => console.log('PAGEERR', String(e)));
await p.goto(`http://127.0.0.1:${srv.address().port}/?barrio=${barrio}`, { waitUntil: 'load' });
await p.waitForFunction(() => window.__pv_listo === true, null, { timeout: 120000 });
await p.click('#boton-jugar');
await new Promise((r) => setTimeout(r, 1500));
const antes = await p.evaluate(() => { const i = window.__pv_info(); return { buses: i.buses, sentados: i.sentados, trafico: i.trafico }; });
console.log('antes:', JSON.stringify(antes));
const robado = await p.evaluate(() => window.__pv_prueba.robarBus());
await new Promise((r) => setTimeout(r, 500));
const despues = await p.evaluate(() => { const i = window.__pv_info(); return { robado: undefined, buses: i.buses, enCoche: i.enCoche, trafico: i.trafico, vehiculo: i.vehiculo.map((v) => Math.round(v * 10) / 10) }; });
console.log('robar el 13:', robado, JSON.stringify(despues), 'aviso:', await p.evaluate(() => document.querySelector('#aviso').textContent));
await p.evaluate(() => window.__pv_prueba.forzarEje(0, 1));
await new Promise((r) => setTimeout(r, 3000));
await p.evaluate(() => window.__pv_prueba.forzarEje(0, 0));
const v2 = await p.evaluate(() => window.__pv_info().vehiculo.map((v) => Math.round(v * 10) / 10));
console.log('conduciendo el 13:', JSON.stringify(v2), 'se mueve:', Math.hypot(v2[0] - despues.vehiculo[0], v2[1] - despues.vehiculo[1]) > 5);
await p.screenshot({ path: `logs/captura-bus.png` });
await b.close(); srv.close();
