// Sonda del menú: portada → créditos, jugar, Escape abre y pausa, garaje, cerrar.
import { chromium } from 'playwright-core';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { join, extname } from 'node:path';
const DIST = '/home/idarroniz/pinoloko/dist';
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.png': 'image/png' };
const srv = createServer(async (req, res) => { let r = new URL(req.url, 'http://x').pathname; if (r.endsWith('/')) r += 'index.html'; try { res.writeHead(200, { 'content-type': MIME[extname(r)] ?? 'application/octet-stream' }); res.end(await readFile(join(DIST, r))); } catch { res.writeHead(404); res.end(); } });
await new Promise((r) => srv.listen(0, '127.0.0.1', r));
const b = await chromium.launch({ executablePath: '/usr/bin/chromium', args: ['--no-sandbox', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 390, height: 844 } });
p.on('console', (m) => { if (m.type() === 'error') console.log('ERR', m.text()); });
p.on('pageerror', (e) => console.log('PAGEERR', String(e)));
await p.goto(`http://127.0.0.1:${srv.address().port}/`, { waitUntil: 'load' });
await p.waitForFunction(() => window.__pv_listo === true, null, { timeout: 120000 });
await p.click('#portada [data-menu="creditos"]');
console.log('créditos visibles:', await p.evaluate(() => document.querySelector('#menu').classList.contains('visible') && document.querySelector('#menu .cuerpo').textContent.includes('OpenStreetMap')));
await p.screenshot({ path: 'logs/captura-creditos.png' });
await p.click('#menu [data-accion="cerrar"]');
await p.click('#boton-jugar');
await new Promise((r) => setTimeout(r, 1500));
await p.keyboard.press('Escape');
await new Promise((r) => setTimeout(r, 300));
const f0 = await p.evaluate(() => window.__pv_frames);
const t0 = await p.evaluate(() => window.__pv_info().vehiculo);
await p.keyboard.down('w'); await new Promise((r) => setTimeout(r, 1500)); await p.keyboard.up('w');
const t1 = await p.evaluate(() => window.__pv_info().vehiculo);
console.log('menú abierto:', await p.evaluate(() => document.querySelector('#menu').classList.contains('visible')), 'frames siguen:', (await p.evaluate(() => window.__pv_frames)) - f0 > 3, 'pausado (no se mueve):', Math.hypot(t1[0] - t0[0], t1[1] - t0[1]) < 0.5);
await p.click('#menu [data-pestana="garaje"]');
console.log('motos en garaje:', await p.evaluate(() => document.querySelectorAll('#menu .moto').length), 'bloqueadas:', await p.evaluate(() => document.querySelectorAll('#menu .moto.bloqueada').length));
await p.screenshot({ path: 'logs/captura-garaje.png' });
await p.click('#menu [data-pestana="estadisticas"]');
console.log('filas stats:', await p.evaluate(() => document.querySelectorAll('#menu .fila').length));
await p.keyboard.press('Escape');
await new Promise((r) => setTimeout(r, 300));
await p.keyboard.down('w'); await new Promise((r) => setTimeout(r, 1500)); await p.keyboard.up('w');
const t2 = await p.evaluate(() => window.__pv_info().vehiculo);
console.log('cerrado y se mueve:', !(await p.evaluate(() => document.querySelector('#menu').classList.contains('visible'))), Math.hypot(t2[0] - t1[0], t2[1] - t1[1]) > 1);
console.log('stats guardadas:', await p.evaluate(() => localStorage.getItem('pinoloko.estadisticas.v1')));
await b.close(); srv.close();
