// Sonda: se planta junto a un ciclista del Sevici y hace una captura; luego lo atropella.
import { chromium } from 'playwright-core';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { join, extname } from 'node:path';
const DIST = new URL('../dist/', import.meta.url).pathname;
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.png': 'image/png' };
const srv = createServer(async (req, res) => { let r = new URL(req.url, 'http://x').pathname; if (r.endsWith('/')) r += 'index.html'; try { res.writeHead(200, { 'content-type': MIME[extname(r)] ?? 'application/octet-stream' }); res.end(await readFile(join(DIST, r))); } catch { res.writeHead(404); res.end(); } });
await new Promise((r) => srv.listen(0, '127.0.0.1', r));
const url = `http://127.0.0.1:${srv.address().port}/?barrio=${process.argv[2] ?? 'pino-montano'}`;
const b = await chromium.launch({ executablePath: '/usr/bin/chromium', args: ['--no-sandbox', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: Number(process.argv[3] ?? 1) });
p.on('console', (m) => { if (m.type() === 'error') console.log('ERR', m.text()); });
p.on('pageerror', (e) => console.log('PAGEERR', String(e)));
await p.goto(url, { waitUntil: 'load' });
await p.waitForFunction(() => window.__pv_listo === true, null, { timeout: 120000 });
await p.click('#boton-jugar');
await p.evaluate(() => window.__pv_prueba.hora(12));
const c = await p.evaluate(() => window.__pv_prueba.sevici()[0]);
console.log('ciclista', JSON.stringify(c));
await p.evaluate(([x, z]) => window.__pv_prueba.irA(x + 3, z + 3, 0), [c.x, c.z]);
await new Promise((r) => setTimeout(r, 1500));
await p.screenshot({ path: 'logs/captura-sevici.png' });
const c2 = await p.evaluate(() => window.__pv_prueba.sevici()[0]);
await p.evaluate(([x, z]) => window.__pv_prueba.irA(x, z + 0.5, 0), [c2.x, c2.z]);
await p.evaluate(() => window.__pv_prueba.empujar(0, -6));
await new Promise((r) => setTimeout(r, 1200));
console.log('tras pasar por encima', JSON.stringify(await p.evaluate(() => ({ c: window.__pv_prueba.sevici()[0], aviso: document.getElementById('aviso').textContent, dinero: document.getElementById('hud-dinero').textContent }))));
await b.close(); srv.close();
