import { chromium } from 'playwright-core';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { join, extname } from 'node:path';
const DIST = '/home/idarroniz/pinoloko/dist';
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.png': 'image/png' };
const srv = createServer(async (req, res) => { let r = new URL(req.url, 'http://x').pathname; if (r.endsWith('/')) r += 'index.html'; try { res.writeHead(200, { 'content-type': MIME[extname(r)] ?? 'application/octet-stream' }); res.end(await readFile(join(DIST, r))); } catch { res.writeHead(404); res.end(); } });
await new Promise((r) => srv.listen(0, '127.0.0.1', r));
const nivel = JSON.parse(await readFile(join(DIST, 'barrios/triana/nivel.json'), 'utf8'));
const agua = nivel.zonas.find((z) => z.clase === 'water').poligono;
const cx = agua.reduce((s, p) => s + p[0], 0) / agua.length, cz = agua.reduce((s, p) => s + p[1], 0) / agua.length;
const b = await chromium.launch({ executablePath: '/usr/bin/chromium', args: ['--no-sandbox', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 390, height: 844 } });
p.on('pageerror', (e) => console.log('PAGEERR', String(e)));
await p.goto(`http://127.0.0.1:${srv.address().port}/?barrio=triana`, { waitUntil: 'load' });
await p.waitForFunction(() => window.__pv_listo === true, null, { timeout: 120000 });
await p.click('#boton-jugar');
await new Promise((r) => setTimeout(r, 800));
await p.evaluate(([x, z]) => window.__pv_prueba.irA(x - 30, z), [cx, cz]);
await new Promise((r) => setTimeout(r, 900));
await p.screenshot({ path: 'logs/captura-rio.png' });
await p.evaluate(([x, z]) => window.__pv_prueba.irA(x, z), [cx, cz]);
await new Promise((r) => setTimeout(r, 900));
console.log('río en', Math.round(cx), Math.round(cz), 'aviso:', await p.evaluate(() => document.querySelector('#aviso').textContent), 'pos:', JSON.stringify(await p.evaluate(() => window.__pv_info().vehiculo.slice(0, 2).map(Math.round))));
await b.close(); srv.close();
